Update customization.md keybinding example (#156)
The `define-key` example provided to bind `s-k` quotes
`kele-command-map` which is not the correct usage. This returns an
error: `Wrong type argument: commandp, kele-command-map` It should
instead use the bare symbol rather than quoting it as we need to call
the keymap itself, not the symbol representing it.